envVarGroups:
  - name: database-vars
    envVars:
      - key: DATABASE_URL
        sync: false # <- Esto le dice a Render que tú pondrás el valor manualmente en su web

services:
  - type: web
    name: ecommerce-frontend
    env: static
    staticPublishPath: frontend/dist
    buildCommand: cd frontend && npm install && npm run build
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://ecommerce-backend-o8ad.onrender.com"

  - type: web
    name: ecommerce-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    envVars:
      - fromGroup: database-vars

  - type: web
    name: ecommerce-phpmyadmin
    env: docker
    plan: free
    dockerfilePath: phpmyadmin/Dockerfile
    envVars:
      - fromGroup: database-vars
      - key: PMA_ABSOLUTE_URI
        value: "https://ecommerce-phpmyadmin.onrender.com"
      - key: PMA_UPLOAD_MAX_FILESIZE
        value: "64M"
      - key: PMA_POST_MAX_SIZE
        value: "64M"
      - key: PMA_MAX_ROWS
        value: "1000"
